syntax = "proto3";
package grpc_sync;


enum Exchange {
  EXCHANGE_UNSPECIFIED = 0;
  POLYMARKET = 1;
  OKX = 2;
}


message PolymarketInstrument{
  uint64 server_id = 1;
  string series_id = 2;
  string series_slug = 3;
  string event_id = 4;
  string event_slug = 5;
  string market_id = 6;
  string market_slug = 7;
  string asset_id = 8;
  string asset_slug = 9;
  uint64 start_ms = 10;
  uint64 end_ms = 11;
  uint64 latest_timestamp = 12;
}

message OkxInstrument{
  uint64 server_id = 1;
  string inst_id = 2;
  string inst_type = 3;
  string inst_family = 4;
  string base_ccy = 5;
  string quote_ccy = 6;
  string settle_ccy = 7;
  uint64 list_time = 8;
  uint64 exp_time = 9;
  double tick_sz = 10;
  double lot_sz = 11;
  double min_sz = 12;
  string alias = 13;
  string state = 14;
  string inst_id_code = 15;
  string inst_category = 16;
}

message Instrument {
  oneof payload {
    PolymarketInstrument polymarket = 1;     // polymarket资产
    OkxInstrument okx = 2;     // okx资产
  }
}

message InstrumentList{
  map<string, Instrument> instruments = 1;
}

// 服务器端和客户端同步的服务
// 这里要提供3个服务
// 1. 获取服务器里面的所有资产的最新时间戳。返回AssetTimestamp
// 2. client提供asset id和timestamp。然后server把timestamp之后的所有数据推送给client。stream里面推送，PolyMarketHistoryList
// 3. 推送信息给client端最新的消息。 PolyMarketHistoryList
service SyncInterface {
  // 1. 获取服务器里面的所有资产的最新时间戳
  rpc ListInstrument(Empty) returns (InstrumentList) {}

  // 2. client提供asset id和timestamp，server把timestamp之后的所有数据推送给client
  rpc SyncHistory(SyncRequest) returns (stream ServerMessage) {}

  // 3. 推送信息给client端最新的消息
  rpc SubscribeLatest(SubscribeRequest) returns (stream ServerMessage) {}
}

message ServerMessage {
  oneof payload {
    PolyMarketHistoryList polymarket_history = 1;     // polymarket
    OkxKlineList okx_kline_history = 2;     // okx kline
  }
}
// 空消息
message Empty {}

// 历史数据同步请求
message SyncRequest {
  uint64 inst_id = 1;   // 资产ID
  uint64 timestamp = 2;  // 起始时间戳，server推送该时间之后的所有数据
  Exchange exchange = 3; // 交易所类型
}

// 订阅最新消息请求
message SubscribeRequest {
  // 预留字段，后续可添加过滤条件（如指定asset_id列表）
}

message PolyMarketHistory {
  uint64 inst_id = 1;
  uint64 timestamp = 2;
  double price = 3;
}

message PolyMarketHistoryList {
  repeated PolyMarketHistory history_list = 1;
  uint64 timestamp = 2;
}

message OkxKline {
  uint64 id = 1;
  string inst_id = 2;
  uint64 ts = 3;
  double open = 4;
  double high = 5;
  double low = 6;
  double close = 7;
  double vol = 8;
  double vol_ccy = 9;
  double vol_ccy_quote = 10;
  uint32 confirm = 11;
}


message OkxKlineList {
  repeated OkxKline kline_list = 1;
  uint64 timestamp = 2;
}
