image: chandlersong/rust_ci:1.85-slim-bookworm-1

stages:
  - test

test:
  stage: test
  before_script:
    - apt-get update  # 更新包列表
    - apt-get install -y libssl-dev  # 安装所需的包
  script:
    - cargo test
  timeout: 10 minutes
  rules:
    - if: $CI_COMMIT_BRANCH == "dev"
