image: rust:1.80.1

stages:
  - test

test:
  stage: test
  before_script:
    - apt-get update -qq
    - apt-get install -y librocksdb-dev clang lld
  script:
    - cargo test
  timeout: 10 minutes
  rules:
    - if: $CI_COMMIT_BRANCH == "dev"
