image: chandlersong/rust_ci:1.85-slim-bookworm.1

stages:
  - test
variables:
  OPENSSL_INCLUDE_DIR: "/usr/include/openssl"
  OPENSSL_LIB_DIR: "/usr/lib/x86_64-linux-gnu"
test:
  stage: test
  script:
    - cargo test
  timeout: 10 minutes
  rules:
    - if: $CI_COMMIT_BRANCH == "dev"
