[workspace]
resolver = "2"



members = [
    "yue",
    "li",
    "yu",
]


[workspace.dependencies]
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.122"
tokio = { version = "1", features = ["full"] }
tokio-cron-scheduler = "*"
sha2 = { version = "0.10.6", default-features = false, features = ["oid"] }
futures = "0.3.32"
hmac = "0.12.0"
rust_decimal = { version = "1.39", features = ["macros"] }
async-trait = "0.1.81"
log = "0.4"
fern = "0.7.1"
humantime = "2.1.0"
sonyflake = "0.4.0"
chrono = "0.4.39"
rocksdb = "0.23.0"
prost = "0.14.1"
prost-build = "0.12"
backon = "1.5.2"
duckdb = { version = "~1.10503.1", features = ["r2d2", "polars"] } # 根据需要添加 feature
thiserror = "2.0.16"
rs-snowflake = "0.6.0"
config = { version = "0.15.16", features = ["yaml"] }
tokio-tungstenite = { version = "0.28.0", features = ["native-tls"] }
tokio-native-tls = "0.3"
futures-util = "0.3.30"
tonic = "0.14.5"
tonic-prost = "0.14.5"          # ← 必须添加这一行
tonic-prost-build = "0.14.5"
governor = { version = "0.10.4", features = ["std"] }
serial_test = "3.5.0"
bon = "3"   # 或最新版本
### DEV ####
mockall = { version = "0.13.1" }

# 网络库
reqwest = { version = "0.12.23", features = ["json", "rustls-tls"] }
reqwest-retry = "0.5"
reqwest-middleware = "0.3"      # 提供 ExponentialBackoff