[package]
name = "yu"
version = "0.1.0"
edition = "2024"

[dependencies]
duckdb = { workspace = true }
tokio = { workspace = true }
futures = { workspace = true }
tokio-cron-scheduler = { workspace = true }
yue = { path = "../yue" }
li = { path = "../li" }
thiserror = { workspace = true }
async-trait = { workspace = true }
log = { workspace = true }
config = { workspace = true }
prost = { workspace = true }
rust_decimal = { workspace = true }
chrono = { workspace = true }
bon = { workspace = true }
rmcp = { version = "0.8.1", features = ["transport-sse-server"] }  # 根据最新版本调整，从 GitHub crate 获取
rmcp-macros = "0.8.1"
governor = { workspace = true }
r2d2 = "0.8.10"


# optional mockall dependency for generating mocks when feature "mockable" is enabled
mockall = { workspace = true, optional = true }

serde = { version = "1.0.225", features = ["derive"] }
serde_json = "1.0"

tonic = { workspace = true }
tonic-prost = { workspace = true }
tokio-stream = "0.1.17"
sqlx = { version = "0.9.0", features = [
    "runtime-tokio",
    "postgres",
    "chrono",
    "uuid",
    "macros", # 如果使用 query! 宏
] }
sqlx-postgres = "0.9.0"
[dev-dependencies]
# keep yue mockable enabled for tests
yue = { path = "../yue", features = ["mockable"] }
# mockall for tests
mockall = { workspace = true }

[features]
mockable = ['mockall']

[build-dependencies]
tonic-prost-build = { workspace = true }
walkdir = "2"          # ← 新增：用于自动扫描所有 .proto 文件