[package]
name = "yu"
version = "0.1.0"
edition = "2024"

[dependencies]
duckdb = { workspace = true }
polars = { workspace = true }
tokio = { workspace = true }
tokio-cron-scheduler = { workspace = true }
yue = { path = "../yue" }
li = { path = "../li" }
thiserror = { workspace = true }
mockall = { workspace = true }
async-trait = { workspace = true }
rs-snowflake = { workspace = true }
log = { workspace = true }
config = { workspace = true }
actix = { workspace = true }
actix-rt = { workspace = true }
prost = { workspace = true }
rust_decimal = { workspace = true }
rmcp = { version = "0.8.1", features = ["transport-sse-server"] }  # 根据最新版本调整，从 GitHub crate 获取
rmcp-macros = "0.8.1"
governor = { workspace = true }
r2d2 = "0.8.10"

serde = { version = "1.0.225", features = ["derive"] }
serde_json = "1.0"

tonic = { workspace = true }
tonic-prost = { workspace = true }
tokio-stream = "0.1.17"


# cron scheduling support
cron = "0.15.0"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.22.0", features = ["v4"] }
dashmap = "6.1.0"
once_cell = "1.21.3"

[dev-dependencies]
tempfile = "3"

[build-dependencies]
tonic-prost-build = { workspace = true }
walkdir = "2"          # ← 新增：用于自动扫描所有 .proto 文件