[package]
name = "nightwatch"
version = "0.1.0"
edition = "2021"

[dependencies]
prometheus = "0.13.4"
lazy_static = "^1.4"
tokio = { version = "^1.0", features = ["macros", "rt-multi-thread"] }
hyper = { version = "^0.14", features = ["server", "http1", "tcp"] }
config =  { version = "^0.14.0", features = ["toml"] }
serde = { version = "1.0.204", features = ["derive"] }
