name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker-practice/actions-setup-qemu@master
      - name: Set up Docker Buildx
        uses: docker-practice/actions-setup-docker@master
      - name: Login to Docker Registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build and push
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64,linux/arm/v7 \
            -t chandlersong/nightwatch:snapshot\
            -f nightwatch/Dockerfile
            --push .
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
