name: unit test
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: chandlersong/rust_ci:1.93-slim-bookworm # 替换为你的镜像
    steps:
      - uses: actions/checkout@v4
      - name: Cache cargo registry and git
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-
      - name: Cache target directory
        uses: actions/cache@v4
        with:
          path: |
            target
            target/**
          key: ${{ runner.os }}-cargo-target-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-target-
      - name: Run cargo test
        run: cargo test --all-features
