name: release
on:
  workflow_dispatch:
    inputs:
      imageTag:
        description: '统一的version'
        required: true
        default: '0.1.5'
      platform:
        description: '支持的平台'
        required: true
        default: 'linux/amd64'
        type: choice
        options:
          - 'linux/amd64,linux/arm64,linux/arm/v7'
          - 'linux/amd64'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run cargo test
        run: cargo test
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: nightwatch build
        uses: docker/build-push-action@v6
        with:
          context: ${{ github.workspace }}
          file: ${{ github.workspace }}/Dockerfile
          push: true
          tags: |
            chandlersong/nightwatch:${{ inputs.imageTag }}
            chandlersong/nightwatch:latest
          build-args: |
            APP_NAME=nightwatch
          platforms: ${{ inputs.platform }}
      - name: direwolf build
        uses: docker/build-push-action@v6
        with:
          context: ${{ github.workspace }}
          file: ${{ github.workspace }}/Dockerfile
          push: true
          tags: |
            chandlersong/nightwatch:${{ inputs.imageTag }}
            chandlersong/nightwatch:latest
          build-args: |
            APP_NAME=direwolf
          platforms: ${{ inputs.platform }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
