name: snapshot
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: rust:1.80-bullseye
    steps:
      - uses: actions/checkout@v2
      - name: Run cargo test
        run: cargo test
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and pushx
        uses: docker/build-push-action@v6
        with:
          context: ${{ github.workspace }}
          file: ${{ github.workspace }}/nightwatch/Dockerfile
          push: true
          tags: chandlersong/nightwatch:snapshot
          platforms: linux/amd64,linux/arm64,linux/arm/v7
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
